Repository FRONTENDSCHOOL8/loocatmydog, pull requests merged in 2024-02, with the labels that each got.

#16 [Feat] Atom StarRating, Button 추가
  public/images/chat.svg
  public/images/google.svg
  public/images/kakao.svg
  public/images/star-fill.svg
  public/images/star.svg
  src/components/atoms/Button/Button.stories.tsx
  src/components/atoms/Button/Button.tsx
  src/components/atoms/StarRating/StarRating.stories.tsx
  src/components/atoms/StarRating/StarRating.tsx
Labels: Feat

#20 Checkbox
  .gitignore
  public/images/checked.svg
  public/images/unchecked.svg
  src/components/atoms/CheckBox/CheckBox.stories.tsx
  src/components/atoms/CheckBox/CheckBox.tsx
Labels: Feat

#22 [BugFix] 스토리북에 스타일 적용되지 않는 문제 수정
  .storybook/preview.ts
  src/styles/reset.css
Labels: BugFix

#23 Button 컴포넌트 수정
  src/components/atoms/Button/Button.stories.tsx
  src/components/atoms/Button/Button.tsx
Labels: Modify

#24 [Design] reset.css 수정
  src/styles/reset.css
Labels: Design

#27 [Design] Button 컴포넌트 수정
  src/components/atoms/Button/Button.tsx
Labels: Design

#29 [Feat] 찜버튼, 캘린더 atom컴포넌트 추가
  package.json
  pnpm-lock.yaml
  public/images/cross.svg
  public/images/direction_left.svg
  public/images/direction_right.svg
  public/images/heart.png
  public/images/heart.svg
  public/images/heart_fill.svg
  src/components/atoms/Calendar/Calendar.stories.tsx
  src/components/atoms/Calendar/Calendar.tsx
  src/components/atoms/HeartButton/HeartButton.stories.tsx
  src/components/atoms/HeartButton/HeartButton.tsx
  src/components/layouts/Rootlayout.tsx
  src/pages/Main.tsx
  src/styles/customDatePicker.css
  src/utils/getDayOfTheWeek.ts
  src/utils/index.ts
Labels: Feat

#30 [Modify] GlobalStyles 설정 및 RootLayout 파일명 수정
  src/components/atoms/ButtonPlus/ButtonPlus.tsx
  src/components/layouts/RootLayout.tsx
  src/index.css
  src/main.tsx
  src/pages/Main.tsx
  src/styles/GlobalStyles.ts
  src/styles/theme.ts
Labels: Modify

#36 [Setting] Storybook GlobalStyles, theme 적용
  .storybook/main.ts
  .storybook/preview.ts
  package.json
  pnpm-lock.yaml
  src/components/atoms/ButtonCheck/ButtonCheck.tsx
  src/styles/theme.ts
Labels: Modify

#39 [Modify] buttonCheck GlobalStyle 적용
  src/components/atoms/ButtonCheck/ButtonCheck.tsx
  src/components/atoms/ButtonPlus/ButtonPlus.stories.tsx
  src/components/atoms/ButtonPlus/ButtonPlus.tsx
  src/components/atoms/CheckBox/CheckBox.tsx
Labels: Modify

#41 [Modify] ButtonCheck type 수정
  public/images/card.svg
  src/components/atoms/ButtonCheck/ButtonCheck.stories.tsx
  src/components/atoms/ButtonCheck/ButtonCheck.tsx
  src/components/molecules/Payment/Payment.stories.tsx
  src/components/molecules/Payment/Payment.tsx
Labels: Modify

#45 [Feat] Header 컴포넌트 구현
  public/images/hamburger.svg
  public/images/plus.svg
  public/images/search.svg
  src/components/Header/Header.tsx
  src/components/molecules/Header/Header.stories.tsx
  src/components/molecules/Header/Header.tsx
  src/components/molecules/SearchInput/SearchInput.stories.tsx
  src/components/molecules/SearchInput/SearchInput.tsx
Labels: Feat

#46 [Modify] styled-components 타입, HeartButton 코드 수정
  src/@types/styled-components.d.ts
  src/components/atoms/HeartButton/HeartButton.tsx
  src/routes/navigation.tsx
  src/styles/theme.ts
Labels: Modify

#47 플레이스 컴포넌트, 인기플레이스 컴포넌트 구현, 버튼 컴포넌트 수정, GlobalStyles 수정, theme 수정
  public/images/place-ex.jpg
  src/components/atoms/Button/Button.tsx
  src/components/molecules/HotPlace/HotPlace.stories.tsx
  src/components/molecules/HotPlace/HotPlace.tsx
  src/components/molecules/Place/Place.stories.tsx
  src/components/molecules/Place/Place.tsx
  src/styles/GlobalStyles.ts
  src/styles/theme.ts
Labels: Feat, Design, Modify

#54 [Modify] checkbox,GlobalStyles 수정
  src/components/atoms/ButtonCheck/ButtonCheck.tsx
  src/components/atoms/ButtonPlus/ButtonPlus.tsx
  src/components/atoms/CheckBox/CheckBox.stories.tsx
  src/components/atoms/CheckBox/CheckBox.tsx
  src/components/molecules/Payment/Payment.tsx
  src/styles/theme.ts
Labels: Modify

#55 [Feat] GlobalNavBar 구현 완료
  public/images/navigation/chatList-active.svg
  public/images/navigation/chatList-inactive.svg
  public/images/navigation/home-active.svg
  public/images/navigation/home-inactive.svg
  public/images/navigation/profile-active.svg
  public/images/navigation/profile-inactive.svg
  public/images/navigation/reservationList-active.svg
  public/images/navigation/reservationList-inactive.svg
  public/images/navigation/stories-active.svg
  public/images/navigation/stories-inactive.svg
  src/components/GlobalNavBar/GlobalNavBar.tsx
  src/components/atoms/BigPhoto/BigPhoto.tsx
  src/components/atoms/DropDown/DropDown.stories.tsx
  src/components/atoms/DropDown/DropDown.tsx
  src/components/atoms/MoreButton/MoreButton.tsx
  src/components/atoms/Photo/Photo.tsx
  src/components/layouts/RootLayout.tsx
  src/components/molecules/GlobalNavBar/GlobalNavBar.stories.tsx
  src/components/molecules/GlobalNavBar/GlobalNavBar.tsx
  src/components/molecules/GlobalNavBar/GlobalNavList.stories.tsx
  src/components/molecules/GlobalNavBar/GlobalNavList.tsx
Labels: Feat

#57 [Feat] StoryCard 컴포넌트 완성
  public/images/story_sample1.jpg
  public/images/story_sample2.jpg
  public/images/story_sample3.jpg
  public/images/story_sample4.jpg
  src/components/layouts/OutletLayout.tsx
  src/components/molecules/StoryCard/StoryCard.stories.tsx
  src/components/molecules/StoryCard/StoryCard.tsx
  src/pages/Main.tsx
  src/utils/convertTime.ts
  src/utils/index.ts
Labels: Feat, Design

#58 [Modify] GlobalNavBar, GlobalNavBarList 코드 수정
  src/components/molecules/GlobalNavBar/GlobalNavBar.tsx
  src/components/molecules/GlobalNavBar/GlobalNavList.tsx
Labels: Modify

#59 [Modify] 채팅 목록 컴포넌트명 변경
  src/components/molecules/ChatRoomList/ChatRoomList.stories.tsx
  src/components/molecules/ChatRoomList/ChatRoomList.tsx
Labels: Modify

#61 [Modify] 컴포넌트 전체적으로 수정
  src/components/atoms/Logo/LogoInline.stories.tsx
  src/components/atoms/Logo/LogoInline.tsx
  src/components/atoms/ProfileImage/ProfileImage.tsx
  src/components/atoms/StateBadge/StateBadeg.stories.tsx
  src/components/atoms/StateBadge/StateBadge.tsx
  src/components/molecules/InputTextArea/InputTextArea.tsx
  src/components/molecules/ProfileListLink/ProfileListLink.tsx
Labels: Modify, Refactor

#63 [Modify] GlobalStyles 버튼 배경 투명 추가
  public/images/plusIcon.svg
  src/assets/test.png
  src/components/atoms/ButtonCheck/ButtonCheck.stories.tsx
  src/components/atoms/ButtonCheck/ButtonCheck.tsx
  src/components/atoms/DateList/DateList.stories.tsx
  src/components/atoms/DateList/DateList.tsx
  src/components/atoms/ProfileCard/ProfileCard.stories.tsx
  src/components/atoms/ProfileCard/ProfileCard.tsx
  src/components/molecules/ProductList/ProductList.stories.tsx
  src/components/molecules/ProductList/ProductList.tsx
  src/styles/GlobalStyles.ts
Labels: Modify

#66 [Modify] 컴포넌트 스타일 컨벤션 수정
  src/components/atoms/Logo/LogoCircle.tsx
  src/components/atoms/Logo/LogoInline.tsx
  src/components/molecules/InputTextArea/InputTextArea.tsx
  src/components/molecules/ProfileListLink/ProfileListLink.tsx
  src/components/molecules/UserProfile/UserProfile.tsx
Labels: Modify

#68 Checkbox
  src/components/A11yHidden/A11yHidden.tsx
  src/components/atoms/CheckBox/CheckBox.stories.tsx
  src/components/atoms/CheckBox/CheckBox.tsx
  src/components/atoms/DateList/DateList.tsx
  src/components/molecules/MyPlaceList/MyPlaceList.stories.tsx
  src/components/molecules/MyPlaceList/MyPlaceList.tsx
Labels: Modify

#69 [Feat] ChatItem 컴포넌트 완성
  index.html
  src/components/atoms/DateDivider/DateDivider.stories.tsx
  src/components/atoms/DateDivider/DateDivider.tsx
  src/components/molecules/ChatItem/ChatItem.stories.tsx
  src/components/molecules/ChatItem/ChatItem.tsx
  src/components/molecules/StoryCard/StoryCard.tsx
  src/pages/Main.tsx
Labels: BugFix, Feat

#70 [Modify] checkboxWrap flex-grow 추가
  src/components/atoms/CheckBox/CheckBox.tsx
Labels: Modify

#71 [modify] 컴포넌트 수정 및 organisms 폴더,파일 생성
  src/components/atoms/Logo/LogoInline.tsx
  src/components/atoms/StateBadge/StateBadge.tsx
  src/components/atoms/Toggle/Toggle.tsx
  src/components/molecules/BooleanBox/BooleanBox.tsx
  src/components/molecules/ProfileListLink/ProfileListLink.tsx
  src/components/molecules/UserProfile/UserProfile.tsx
  src/components/organisms/MyPage/MyPage.stories.tsx
  src/components/organisms/MyPage/MyPage.tsx
  src/routes/navigation.tsx
Labels: Feat, Modify

#74 [Modify] NameInput 을 FormInput으로 수정
  src/components/atoms/StateBadge/StateBadge.tsx
  src/components/molecules/FormInput/FormInput.stories.tsx
  src/components/molecules/FormInput/FormInput.tsx
  src/components/molecules/NameInput/NameInput.tsx
Labels: Modify, Refactor

#75 [Refactor] Header 및 StoryCard 컴포넌트 리팩토링
  public/images/more.svg
  src/components/molecules/Header/Header.stories.tsx
  src/components/molecules/Header/Header.tsx
  src/components/molecules/StoryCard/StoryCard.stories.tsx
  src/components/molecules/StoryCard/StoryCard.tsx
  src/styles/GlobalStyles.ts
Labels: Feat, Refactor

#77 [Modify] 파비콘 및 atoms, molecules, organisms 수정
  index.html
  src/components/atoms/StateBadge/StateBadge.tsx
  src/components/atoms/Toggle/Toggle.tsx
  src/components/molecules/BooleanBox/BooleanBox.tsx
  src/components/molecules/UserProfile/UserProfile.tsx
  src/components/organisms/MyPage/MyPage.tsx
  src/components/organisms/Settings/Settings.tsx
  src/routes/navigation.tsx
Labels: Feat, Modify, Refactor

#79 [Modify] checkbox, dateList 수정
  src/components/atoms/CheckBox/CheckBox.tsx
  src/components/atoms/DateList/DateList.tsx
  src/components/molecules/MyPlaceList/MyPlaceList.tsx
Labels: Modify

#81 [Modify] ProfileCard 수정
  src/components/atoms/CheckBox/CheckBox.tsx
  src/components/molecules/AnimalRateInput/AnimalRateInput.tsx
  src/components/molecules/InputTypes/InputTypes.stories.tsx
  src/components/molecules/InputTypes/InputTypes.tsx
  src/components/molecules/Payment/Payment.tsx
  src/components/molecules/ProfileCard/ProfileCard.tsx
Labels: Modify

#85 [Modify] ProfileCard 컴포넌트 수정
  public/images/camera.svg
  public/images/profileIconNone.svg
  public/images/profileNone.svg
  src/components/atoms/DateList/DateList.tsx
  src/components/molecules/AnimalRateInput/AnimalRateInput.tsx
  src/components/molecules/MyPlaceList/MyPlaceList.tsx
  src/components/molecules/ProfileCard/ProfileCard.tsx
  src/styles/theme.ts
Labels: Modify

#86 [Modify] BigPhoto, Photo, DropDown, MoreButton 수정
  public/images/xIcon.svg
  src/@types/swiper.d.ts
  src/components/atoms/BigPhoto/BigPhoto.stories.tsx
  src/components/atoms/BigPhoto/BigPhoto.tsx
  src/components/atoms/DropDown/DropDown.tsx
  src/components/atoms/MoreButton/MoreButton.tsx
  src/components/atoms/Photo/Photo.tsx
  src/components/molecules/ImageSwiper/ImageSwiperContainer.stories.tsx
  src/components/molecules/ImageSwiper/ImageSwiperContainer.tsx
  src/components/molecules/ImageSwiper/ImageSwiperSlide.stories.tsx
  src/components/molecules/ImageSwiper/ImageSwiperSlide.tsx
  src/hooks/useStateRef.ts
  src/routes/navigation.tsx
  src/utils/getRefValue.ts
  tsconfig.json
Labels: Modify

#87 [feat] 찜목록, 내 정보 수정 페이지 구현
  public/images/innerImg.jpg
  src/components/organisms/HeartList/HeartList.stories.tsx
  src/components/organisms/HeartList/HeartList.tsx
  src/components/organisms/ModifyProfile/ModifyProfile.stories.tsx
  src/components/organisms/ModifyProfile/ModifyProfile.tsx
  src/components/organisms/MyPage/MyPage.tsx
Labels: Feat, Modify

#88 코드 리뷰 부분 수정
  src/components/atoms/Button/Button.stories.tsx
  src/components/atoms/Button/Button.tsx
  src/components/atoms/StarRating/StarRating.stories.tsx
  src/components/atoms/StarRating/StarRating.tsx
  src/components/molecules/ChatRoomList/ChatRoomList.stories.tsx
  src/components/molecules/ChatRoomList/ChatRoomList.tsx
  src/components/molecules/HotPlace/HotPlace.stories.tsx
  src/components/molecules/HotPlace/HotPlace.tsx
  src/components/molecules/Place/Place.stories.tsx
  src/components/molecules/Place/Place.tsx
  src/utils/comma.ts
  src/utils/convertTime.ts
  src/utils/index.ts
Labels: BugFix, Feat, Design, Modify
