Repository FRONTENDSCHOOL8/loocatmydog, pull requests merged in 2024-03, with the labels that each got.

#90 [Feat] InputTypes 컴포넌트 구현
  src/components/atoms/CheckBox/CheckBox.tsx
  src/components/atoms/InputWrapper/InputWrapper.stories.tsx
  src/components/atoms/InputWrapper/InputWrapper.tsx
  src/components/molecules/AnimalRateInput/AnimalRateInput.stories.tsx
  src/components/molecules/AnimalRateInput/AnimalRateInput.tsx
  src/components/molecules/InputTypes/InputTypes.stories.tsx
  src/components/molecules/InputTypes/InputTypes.tsx
Labels: Feat, Modify

#91 StarRating 컴포넌트 수정, ChatRoomList 컴포넌트 기능 추가, Button 컴포넌트 수정
  src/components/atoms/Button/Button.stories.tsx
  src/components/atoms/Button/Button.tsx
  src/components/atoms/StarRating/StarRating.stories.tsx
  src/components/atoms/StarRating/StarRating.tsx
  src/components/molecules/ChatRoomList/ChatRoomList.stories.tsx
  src/components/molecules/ChatRoomList/ChatRoomList.tsx
Labels: Feat, Modify

#94 [feat] 반려동물 추가 컴포넌트 추가
  src/components/molecules/InputTextArea/InputTextArea.tsx
  src/components/molecules/Tab/Tab.stories.tsx
  src/components/molecules/Tab/Tab.tsx
  src/components/organisms/AddPet/AddPet.tsx
  src/components/organisms/ModifyProfile/ModifyProfile.tsx
  src/routes/navigation.tsx
Labels: Feat, Modify

#93 [Feat] 플레이스 중간저장
  src/components/atoms/ButtonPlus/ButtonPlus.stories.tsx
  src/components/atoms/ButtonPlus/ButtonPlus.tsx
  src/components/organisms/PlaceTitle/PlaceTitle.stories.tsx
  src/components/organisms/PlaceTitle/PlaceTitle.tsx
  src/components/organisms/SwiperProfile/SwiperProfile.stories.tsx
  src/components/organisms/SwiperProfile/SwiperProfile.tsx
  src/pages/Place.tsx
  src/utils/index.ts
  src/utils/maskingName.ts
Labels: Feat

#95 [Modify] Header 및 Calendar 컴포넌트 코드 리팩토링, router 객체 재구성, pocketbase api 추가
  package.json
  pnpm-lock.yaml
  src/api/pocketbase.ts
  src/components/atoms/Calendar/Calendar.stories.tsx
  src/components/atoms/Calendar/Calendar.tsx
  src/components/layouts/RootLayout.tsx
  src/components/molecules/Header/Header.tsx
  src/components/molecules/SearchInput/SearchInput.stories.tsx
  src/components/molecules/SearchInput/SearchInput.tsx
  src/pages/Main.tsx
  src/pages/Main/Main.tsx
  src/pages/PlaceList/PlaceList.tsx
  src/routes/index.tsx
  src/routes/navigation.tsx
  src/store/useDateRange.ts
  src/styles/customDatePicker.css
Labels: Feat, Modify, Setting

#96 [Modify] RootLayout.tsx 수정 (GlobalNavBar 출력 관련)
  src/components/layouts/RootLayout.tsx
Labels: Modify

#101 [Feat] Splash 컴포넌트 UI 구현
  public/images/pet-splash.png
  src/components/organisms/Splash/Splash.stories.tsx
  src/components/organisms/Splash/Splash.tsx
Labels: Feat

#102 [Feat] Landing 페이지 UI 구현
  public/images/pet-landing.jpg
  src/pages/Landing/Landing.tsx
  src/routes/navigation.tsx
Labels: Feat

#103 [BugFix] Place 컴포넌트 내 StarRating 컴포넌트 오류 수정
  src/components/atoms/StarRating/StarRating.tsx
  src/components/molecules/Place/Place.tsx
Labels: BugFix

#104 [Feat] 사이드메뉴 컴포넌트 마크업 및 스타일링
  public/images/sidemenu/events.svg
  public/images/sidemenu/heart.svg
  public/images/sidemenu/myplace.svg
  public/images/sidemenu/sidebar_dog.png
  public/images/sidemenu/story.svg
  src/components/layouts/RootLayout.tsx
  src/components/molecules/Header/Header.stories.tsx
  src/components/molecules/Header/Header.tsx
  src/components/organisms/SideMenu/SideMenu.stories.tsx
  src/components/organisms/SideMenu/SideMenu.tsx
  src/pages/Main/Main.tsx
  src/routes/navigation.tsx
  src/styles/GlobalStyles.ts
Labels: Feat, Refactor

#105 [Feat] 회원가입 페이지 UI 구현중
  public/images/pet-signUp.png
  src/components/organisms/SignUp/SignUpAddress.stories.tsx
  src/components/organisms/SignUp/SignUpAddress.tsx
  src/components/organisms/SignUp/SignUpAgree.stories.tsx
  src/components/organisms/SignUp/SignUpAgree.tsx
  src/components/organisms/SignUp/SignUpEmail.stories.tsx
  src/components/organisms/SignUp/SignUpEmail.tsx
  src/components/organisms/SignUp/SignUpPhone.stories.tsx
  src/components/organisms/SignUp/SignUpPhone.tsx
Labels: Feat

#106 [Modify] 프로필에 사진 입력추가, pb 연결 시도 및 모달 시도
  package.json
  pnpm-lock.yaml
  src/@types/test.d.ts
  src/components/molecules/FormInput/FormInput.tsx
  src/components/molecules/UserProfile/UserProfile.tsx
  src/components/organisms/AddPet/AddPet.tsx
  src/components/organisms/ModifyProfile/ModifyProfile.tsx
  src/components/organisms/PlaceList/PlaceList.tsx
Labels: Feat, Modify

#107 [Modify] Swiper 컴포넌트 수정
  public/images/bigXIcon.svg
  src/components/atoms/BigPhoto/BigPhoto.tsx
  src/components/atoms/Photo/Photo.tsx
  src/components/molecules/ImageSwiper/ContentSwiperContainer.tsx
  src/components/molecules/ImageSwiper/ImageSwiperContainer.tsx
  src/components/organisms/Stories/Stories.stories.tsx
  src/components/organisms/Stories/Stories.tsx
  src/components/organisms/Stories/StoryWrite.stories.tsx
  src/components/organisms/Stories/StoryWrite.tsx
  src/components/organisms/Stories/pocketbase.ts
  src/hooks/useFirstPathName.ts
  src/routes/navigation.tsx
  src/utils/getFirstPathName.ts
Labels: Modify

#108 [Modify] FormInput props 수정 ModifyProfile 수정
  src/components/molecules/FormInput/FormInput.tsx
  src/components/organisms/ModifyProfile/ModifyProfile.tsx
  src/components/organisms/Settings/Settings.tsx
Labels: BugFix, Modify

#109 [Feat] PlaceSection 및 DatePick 형태잡기
  src/components/molecules/PlaceSection/PlaceSection.stories.tsx
  src/components/molecules/PlaceSection/PlaceSection.tsx
  src/components/organisms/DatePick/DatePick.stories.tsx
  src/components/organisms/DatePick/DatePick.tsx
Labels: Feat

#110 [Feat] 회원가입 약관동의 컴포넌트, 이메일입력 컴포넌트 구현
  src/components/organisms/SignUp/SignUpAgree.tsx
  src/components/organisms/SignUp/SignUpEmail.tsx
  src/hooks/useInput.ts
  src/pages/SignUp/SignUp.tsx
  src/routes/navigation.tsx
  src/utils/signUpValidation.ts
Labels: Feat

#111 [Modify] ModifyProfile 거의 완성
  src/components/molecules/InputTypes/InputTypes.tsx
  src/components/organisms/AddPet/AddPet.tsx
  src/components/organisms/ModifyProfile/ModifyProfile.tsx
  src/components/organisms/MyPage/MyPage.tsx
Labels: BugFix

#112 [feat] KakaoMap API 컴포넌트 등록
  index.html
  src/components/atoms/KakaoMap/KakaoMap.tsx
Labels: Feat

#113 [Modify] ContentSwiperContainer 수정, StoryWrite 구현
  src/api/pocketbase.ts
  src/components/atoms/DropDown/DropDown.tsx
  src/components/molecules/ImageSwiper/ContentSwiperContainer.tsx
  src/components/molecules/ImageSwiper/ImageSwiperContainer.tsx
  src/components/molecules/Tab/Tab.tsx
  src/components/organisms/Stories/Stories.tsx
  src/components/organisms/Stories/StoryWrite.tsx
  src/components/organisms/Stories/pocketbase.ts
  src/routes/navigation.tsx
Labels: Modify

#114 [Modify] ProfileCard 수정
  src/components/molecules/InputTypes/InputTypes.tsx
  src/components/molecules/ProfileCard/ProfileCard.stories.tsx
  src/components/molecules/ProfileCard/ProfileCard.tsx
  src/components/organisms/AnimalPick/AnimalPick.stories.tsx
  src/components/organisms/AnimalPick/AnimalPick.tsx
Labels: Modify

#115 [Feat] Main 페이지 마크업 및 스타일링
  src/components/A11yHidden/A11yHidden.tsx
  src/components/atoms/Calendar/Calendar.tsx
  src/components/layouts/OutletLayout.tsx
  src/components/layouts/RootLayout.tsx
  src/components/molecules/Header/Header.tsx
  src/components/molecules/SearchInput/SearchInput.tsx
  src/components/organisms/SideMenu/SideMenu.tsx
  src/pages/Main/Main.tsx
  src/routes/navigation.tsx
  src/store/useModalControl.ts
Labels: BugFix, Feat, Design, Refactor

#116 회원가입 페이지 구현중
  src/components/molecules/FormInput/FormInput.tsx
  src/components/organisms/SignUp/SignUpAddress.tsx
  src/components/organisms/SignUp/SignUpAgree.tsx
  src/components/organisms/SignUp/SignUpEmail.tsx
  src/components/organisms/SignUp/SignUpHeader.tsx
  src/components/organisms/SignUp/SignUpPhone.tsx
  src/pages/SignUp/SignUp.tsx
  src/utils/getRandomNumber.ts
  src/utils/index.ts
  src/utils/signUpValidation.ts
Labels: Feat

#119 [Feat] getPbImageURL 함수 생성
  src/components/molecules/ImageSwiper/ImageSwiperContainer.tsx
  src/components/organisms/Stories/Stories.tsx
  src/components/organisms/Stories/StoryWrite.tsx
  src/utils/getPbImageURL.ts
Labels: Feat

#120 [Modify] AddPet 컴포넌트와 데이터베이스 연결
  src/components/atoms/Button/Button.tsx
  src/components/atoms/CheckBox/CheckBox.tsx
  src/components/molecules/InputTypes/InputTypes.tsx
  src/components/molecules/UserProfile/UserProfile.tsx
  src/components/organisms/AddPet/AddPet.tsx
  src/components/organisms/MyPage/MyPage.tsx
  src/components/organisms/PlaceList/PlaceList.tsx
  src/routes/navigation.tsx
Labels: BugFix, Modify

#122 [Feat] PlaceList 페이지 마크업 및 스타일링
  index.html
  public/favicon/apple-touch-icon.png
  public/favicon/favicon-16x16.png
  public/favicon/favicon-32x32.png
  public/favicon/safari-pinned-tab.svg
  src/components/atoms/DropDown/DropDown.tsx
  src/components/atoms/FilterButton/FilterButton.tsx
  src/components/layouts/OutletLayout.tsx
  src/components/layouts/RootLayout.tsx
  src/components/molecules/SearchInput/SearchInput.tsx
  src/components/molecules/StoryCard/StoryCard.tsx
  src/data/dummyPlaceData.ts
  src/hooks/useGetAllSearchParams.ts
  src/pages/Main/Main.tsx
  src/pages/Main/StyledMain.ts
  src/pages/PlaceList/PlaceList.tsx
  src/pages/PlaceList/StyledPlaceList.ts
Labels: Feat, Design, Refactor

#123 [Feat] 회원가입 페이지 주소 선택시 위도, 경도 가져오기
  src/components/organisms/SignUp/SignUpAddress.tsx
  src/pages/SignUp/SignUp.tsx
  src/routes/navigation.tsx
  src/utils/getGeolocation.ts
Labels: Feat

#124 [Feat] Story, StoryWrite 페이지 구현
  src/components/atoms/BigPhoto/BigPhoto.tsx
  src/components/molecules/StoryCard/StoryCard.tsx
  src/components/organisms/Reservations/Reservations.stories.tsx
  src/components/organisms/Reservations/Reservations.tsx
  src/components/organisms/Stories/Stories.tsx
  src/components/organisms/Stories/StoryWrite.tsx
  src/routes/navigation.tsx
Labels: Feat

#125 [BugFix] 위도, 경도 구하는 util 함수 수정, [Feat] 회원가입 form 제출 방식 onSubmit으로 변경
  src/components/organisms/SignUp/SignUpAddress.tsx
  src/pages/SignUp/SignUp.tsx
  src/utils/getGeolocation.ts
Labels: BugFix

#126 [Refactor] 여러가지 코드 리팩토링
  .eslintrc.cjs
  src/@types/database.d.ts
  src/api/pocketbase.ts
  src/components/layouts/OutletLayout.tsx
  src/components/molecules/ImageSwiper/ImageSwiperContainer.tsx
  src/components/organisms/AnimalPick/AnimalPick.stories.tsx
  src/components/organisms/AnimalPick/AnimalPick.tsx
  src/components/organisms/ModifyProfile/ModifyProfile.tsx
  src/pages/Main/Main.tsx
  src/routes/navigation.tsx
  tsconfig.json
Labels: Refactor

#127 [Modify] AddPet 폼제어 추가
  src/@types/test.d.ts
  src/components/atoms/CheckBox/CheckBox.tsx
  src/components/atoms/InputWrapper/InputWrapper.tsx
  src/components/atoms/PetIcon/PetIcon.tsx
  src/components/molecules/InputTextArea/InputTextArea.tsx
  src/components/molecules/InputTypes/InputTypes.tsx
  src/components/molecules/ProfileCard/ProfileCard.tsx
  src/components/organisms/AddPet/AddPet.tsx
  src/components/organisms/ModifyProfile/ModifyProfile.tsx
  src/components/organisms/MyPage/MyPage.tsx
Labels: BugFix, Modify

#128 Feat/signup
  src/pages/SignUp/SignUp.tsx
  src/routes/navigation.tsx
Labels: Feat

#131 [Feat]Place 구현 중간 저장
  index.html
  src/components/atoms/CheckBox/CheckBox.tsx
  src/components/organisms/AnimalPick/AnimalPick.tsx
  src/components/organisms/DatePick/DatePick.tsx
  src/components/organisms/PlaceIntroduce/PlaceIntroduce.tsx
  src/components/organisms/PlaceLocation/PlaceLocation.tsx
  src/components/organisms/ServiceCanUse/ServiceCanUse.tsx
  src/components/organisms/ServicePrice/ServicePrice.tsx
  src/data/service.ts
  src/routes/navigation.tsx
  src/store/useUserStore.ts
  src/utils/getPbImageURL.ts
  src/utils/pb.ts
Labels: Feat

#132 [Feat] 메인 페이지 포켓베이스 데이터 연동
  database_d.ts
  public/images/sidemenu/sidebar_dog_small.png
  src/components/layouts/RootLayout.tsx
  src/components/molecules/Place/Place.tsx
  src/components/molecules/ShortcutMenu/ShortcutMenu.tsx
  src/hooks/usePlaceList.ts
  src/pages/Main/Main.tsx
  src/pages/Main/StyledMain.ts
  src/pages/Main/index.ts
  src/pages/Main/loader.ts
  src/routes/navigation.tsx
Labels: BugFix, Feat, Refactor

#133 [Modify] 타입 오류 수정
  src/pages/Place.tsx
  src/pages/PlaceList/PlaceList.tsx
Labels: BugFix, Refactor

#134 [Chore] 배포 시도 테스트
  .gitignore
  src/main.tsx
  vite.config.ts
Labels: Chore

#135 [Feat] 로그인 페이지 구현
  src/pages/SignIn/SignIn.tsx
  src/routes/navigation.tsx
  src/store/types.d.ts
  src/store/useAuthStore.ts
  src/utils/getStorage.ts
Labels: Feat

#136 [Chore] netlify 배포시 필요한 파일 생성 및 BrowserRouter 삭제
  netlify.toml
  package.json
  pnpm-lock.yaml
  src/main.tsx
Labels: BugFix, Chore

#138 [Feat] PlaceDetail 리뷰, 스와이퍼 제외 구현
  index.html
  src/@types/database.d.ts
  src/components/atoms/ButtonCheck/ButtonCheck.tsx
  src/components/molecules/InputTextArea/InputTextArea.tsx
  src/components/molecules/ProfileCard/ProfileCard.tsx
  src/components/organisms/AnimalPick/AnimalPick.tsx
  src/components/organisms/DatePick/DatePick.tsx
  src/components/organisms/ServiceCanUse/ServiceCanUse.tsx
  src/data/service.ts
  src/pages/PlaceDetail/PlaceDetail.tsx
  src/pages/PlaceDetail/loader.ts
  src/routes/navigation.tsx
  src/store/useCheckboxStore.ts
  src/utils/index.ts
  src/utils/pb.ts
  src/utils/sizeWeight.ts
Labels: Feat

#139 [Modify] 메인 페이지 및 기타 컴포넌트 코드 수정
  src/@types/database.d.ts
  src/api/fetchPlaceList.ts
  src/components/atoms/Calendar/Calendar.tsx
  src/pages/Main/Main.tsx
  src/pages/Main/loader.ts
  src/pages/PlaceList/PlaceList.tsx
  src/pages/PlaceList/index.ts
  src/routes/navigation.tsx
Labels: BugFix, Modify

#141 [Feat] 채팅 목록, 채팅 방 구현 중
  public/images/iconSend.svg
  src/components/atoms/DropDown/DropDown.tsx
  src/components/molecules/ImageSwiper/ImageSwiperContainer.tsx
  src/pages/ChatList/ChatList.tsx
  src/pages/ChatList/getChatListData.tsx
  src/pages/ChatList/useChatListData.tsx
  src/pages/ChatRoom/ChatRoom.tsx
  src/pages/ChatRoom/createChatRoom.tsx
  src/pages/ChatRoom/getChatRoomData.tsx
  src/pages/ChatRoom/setChatRead.tsx
  src/pages/ChatRoom/useChatRoomData.tsx
  src/routes/navigation.tsx
  src/utils/getPbImageURL.ts
Labels: Feat

#140 [Modify] 로그인 시 localstorage와 state에 저장되는 데이터 추가
  src/store/useAuthStore.ts
Labels: Modify

#144 [Modify] MyPage 페이지, ModifyProfile 페이지 수정
  src/components/organisms/ModifyProfile/ModifyProfile copy.tsx
  src/components/organisms/ModifyProfile/ModifyProfile.tsx
  src/components/organisms/MyPage/MyPage.tsx
Labels: Modify, Refactor

#145 [Feat] PlaceDetail 수정, MyPlaceList state 추가
  src/components/atoms/DateList/DateList.tsx
  src/components/molecules/MyPlaceList/MyPlaceList.tsx
  src/components/organisms/AnimalPick/AnimalPick.tsx
  src/components/organisms/DatePick/DatePick.tsx
  src/components/organisms/PlaceTitle/PlaceTitle.tsx
  src/components/organisms/ServiceCanUse/ServiceCanUse.tsx
  src/components/organisms/ServicePrice/ServicePrice.tsx
  src/pages/PlaceDetail/PlaceDetail.tsx
  src/pages/PlaceDetail/loader.ts
Labels: Feat

#146 [Feat] 소셜로그인 기능 추가
  src/@types/database.d.ts
  src/pages/Landing/Landing.tsx
  src/pages/SignUp/SignUp.tsx
  src/store/useAuthStore.ts
  src/utils/googleLogin.ts
  src/utils/kakaoLogin.ts
Labels: Feat

#148 회원가입 페이지 수정
  src/components/organisms/SignUp/SignUpAddress.tsx
  src/components/organisms/SignUp/SignUpPhone.tsx
Labels: BugFix, Modify

#147 [feat] NotFoundPage 구현
  public/images/catdogs.jpg
  public/images/editPen.svg
  src/components/molecules/UserProfile/UserProfile.tsx
  src/components/organisms/MyPage/MyPage.stories.tsx
  src/main.tsx
  src/pages/AddPet/AddPet.tsx
  src/pages/ModifyProfile/ModifyProfile.stories.tsx
  src/pages/ModifyProfile/ModifyProfile.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/NotFoundPage/NotFoundPage.tsx
  src/pages/Settings/Settings.tsx
  src/routes/navigation.tsx
Labels: Feat

#149 [Feat] 회원가입 이메일, 휴대폰번호 중복 체크 기능 추가
  src/components/organisms/SignUp/SignUpEmail.tsx
  src/components/organisms/SignUp/SignUpPhone.tsx
  src/hooks/useInput.ts
  src/pages/SignUp/SignUp.tsx
  src/utils/debounce.ts
Labels: Feat, Modify

#152 [Feat]Place 중간 저장 및 DateRange 초기화 추가
  database.d.ts
  src/@types/database.d.ts
  src/components/molecules/MyPlaceList/MyPlaceList.tsx
  src/components/organisms/AnimalPick/AnimalPick.tsx
  src/components/organisms/PlaceIntroduce/PlaceIntroduce.tsx
  src/components/organisms/PlaceLocation/PlaceLocation.tsx
  src/components/organisms/PlaceReview/PlaceReview.tsx
  src/components/organisms/SwiperProfile/SwiperProfile.tsx
  src/pages/PlaceDetail/PlaceDetail.tsx
  src/pages/PlaceDetail/loader.ts
  src/routes/navigation.tsx
  src/store/useCheckboxStore.ts
Labels: Feat

#153 [Refactor] 메인 및 플레이스리스트 전체적인 리팩토링
  index.html
  public/images/home.svg
  src/api/fetchPlaceList.ts
  src/components/layouts/RootLayout.tsx
  src/components/molecules/Header/Header.tsx
  src/components/molecules/SearchInput/SearchInput.tsx
  src/components/organisms/SideMenu/SideMenu.tsx
  src/hooks/usePlaceFilter.ts
  src/hooks/usePlaceList.ts
  src/hooks/usePlaceSort.ts
  src/hooks/useSearchDate..ts
  src/pages/Main/Main.tsx
  src/pages/Main/loader.ts
  src/pages/PlaceList/PlaceList.tsx
  src/pages/PlaceList/StyledPlaceList.ts
  src/routes/navigation.tsx
  src/utils/calculateDistanceByCoords.ts
  src/utils/convertFilterString.ts
  src/utils/getDistanceByAddress.ts
  src/utils/getQueryOptions.ts
Labels: BugFix, Feat, Refactor

#154 [Feat] 결제 페이지까지 UI 구현 완료
  public/images/paymentBanner.jpg
  src/components/molecules/PaymentCard/PaymentCard.stories.tsx
  src/components/molecules/PaymentCard/PaymentCard.tsx
  src/components/molecules/PlaceSection/PlaceSection.tsx
  src/components/organisms/AnimalPick/AnimalPick.tsx
  src/components/organisms/DatePick/DatePick.tsx
  src/components/organisms/PlaceReview/PlaceReview.tsx
  src/components/organisms/PlaceTitle/PlaceTitle.tsx
  src/components/organisms/ReservationInfo/ReservationInfo.tsx
  src/components/organisms/ServiceCanUse/ServiceCanUse.tsx
  src/components/organisms/SwiperProfile/SwiperProfile.tsx
  src/pages/AddPlace/AddPlace.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/Payment/Payment.tsx
  src/pages/PlaceDetail/PlaceDetail.tsx
  src/pages/PlaceDetail/loader.ts
  src/routes/navigation.tsx
  src/store/useReservationStore.ts
Labels: Feat

#155 [Modify] API Key 삭제
  index.html
  src/utils/getGeolocation.ts
Labels: Modify

#156 [Feat] 예약 내역, 리뷰 작성하기 구현
  src/@types/database.d.ts
  src/components/atoms/BigPhoto/BigPhoto.tsx
  src/components/atoms/ButtonPlus/ButtonPlus.tsx
  src/components/atoms/DateList/DateList.tsx
  src/components/atoms/StateBadge/StateBadge.tsx
  src/components/molecules/GlobalNavBar/GlobalNavBar.tsx
  src/components/molecules/ImageSwiper/ImageSwiperContainer.tsx
  src/components/molecules/MyPlaceList/MyPlaceList.tsx
  src/components/organisms/Reservations/Reservations.stories.tsx
  src/components/organisms/Reservations/Reservations.tsx
  src/components/organisms/Stories/Stories.stories.tsx
  src/components/organisms/Stories/StoryWrite.stories.tsx
  src/pages/ChatList/ChatList.tsx
  src/pages/ChatRoom/ChatRoom.tsx
  src/pages/ChatRoom/compareDate.tsx
  src/pages/ChatRoom/createChatRoom.tsx
  src/pages/ChatRoom/getChatRoomData.tsx
  src/pages/Reservations/Reservations.tsx
  src/pages/Reservations/getReservations.tsx
  src/pages/Reservations/useReservationData.tsx
  src/pages/Stories/Stories.tsx
  src/pages/StoriesWrite/StoryWrite.tsx
  src/routes/navigation.tsx
  src/utils/convertDate.ts
  src/utils/getDateDiff.ts
Labels: Feat, Modify

#159 [Modify] 리뷰페이지 별점, 플레이스 상세페이지 문의 구현
  src/pages/ChatList/getChatListData.tsx
  src/pages/ChatRoom/ChatRoom.tsx
  src/pages/ChatRoom/createChatRoom.tsx
  src/pages/ChatRoom/getChatRoomData.tsx
  src/pages/PlaceDetail/PlaceDetail.tsx
  src/pages/StoriesWrite/StoryWrite.tsx
Labels: Modify

#160 [Feat] 찜목록, 마이플레이스 페이지 구현
  package.json
  pnpm-lock.yaml
  src/components/molecules/MyPlaceList/MyPlaceList.tsx
  src/components/molecules/Place/Place.tsx
  src/components/organisms/HeartList/HeartList.tsx
  src/pages/HeartPlaces/HeartPlaces.tsx
  src/pages/HeartPlaces/index.ts
  src/pages/HeartPlaces/loader.ts
  src/pages/Main/Main.tsx
  src/pages/MyPlaces/MyPlaces.tsx
  src/pages/PlaceList/PlaceList.tsx
  src/routes/navigation.tsx
  src/utils/convertFilterString.ts
Labels: Feat, Refactor

#161 [BugFix] PlaceList 타입 오류 수정
  src/pages/PlaceList/PlaceList.tsx
Labels: BugFix

#162 [Feat] protected route 설정 (로그인 접근 제한)
  src/components/layouts/RootLayout.tsx
  src/pages/Landing/Landing.tsx
  src/pages/SignUp/SignUp.tsx
  src/routes/Authorization.tsx
  src/routes/navigation.tsx
Labels: Feat

#163 [Modify] : ImageSwiperContainer, BigPhoto, Photo 수정
  src/components/atoms/BigPhoto/BigPhoto.tsx
  src/components/atoms/Photo/Photo.tsx
  src/components/molecules/ImageSwiper/ImageSwiperContainer.tsx
  src/pages/ChatRoom/ChatRoom.tsx
  src/pages/Stories/Stories.tsx
Labels: Modify

#164 [Modify] 캘린더 컴포넌트 코드 수정
  src/components/atoms/Calendar/Calendar.tsx
Labels: Modify

#165 [Modify] story 오류, 빈 예약 내역 글 생성 구현
  src/components/atoms/ButtonPlus/ButtonPlus.tsx
  src/components/molecules/StoryCard/StoryCard.tsx
  src/pages/ChatRoom/ChatRoom.tsx
  src/pages/Reservations/Reservations.tsx
  src/pages/Stories/Stories.tsx
Labels: BugFix, Modify

#167 Place
  src/components/molecules/AnimalRateInput/AnimalRateInput.tsx
  src/components/molecules/ImageSwiper/ImageSwiperContainer.tsx
  src/components/organisms/AnimalPick/AnimalPick.tsx
  src/components/organisms/PlaceLocation/PlaceLocation.tsx
  src/pages/AddPlace/AddPlace.tsx
  src/pages/PlaceDetail/loader.ts
  src/routes/navigation.tsx
Labels: Modify

#168 [Refactor] StoryWrite 접근성 측면 리팩토링
  src/pages/StoriesWrite/StoryWrite.tsx
Labels: Refactor

#170 [Docs] README 작성
  README.md
Labels: Docs

#171 [Feat] 팝업 배너, 메인 이미지 캐러셀, 로딩 UI 및 코드 리팩토링
  src/@types/database.d.ts
  src/app/App.tsx
  src/components/atoms/DropDown/DropDown.tsx
  src/components/layouts/OutletLayout.tsx
  src/components/layouts/RootLayout.tsx
  src/components/molecules/EventPopup/EventPopup.stories.tsx
  src/components/molecules/EventPopup/EventPopup.tsx
  src/components/molecules/Header/Header.tsx
  src/components/molecules/LoadingSpinner/LoadingSpinner.stories.tsx
  src/components/molecules/LoadingSpinner/LoadingSpinner.tsx
  src/components/organisms/SideMenu/SideMenu.tsx
  src/hooks/usePlaceFilter.ts
  src/pages/Main/Main.tsx
  src/pages/Main/loader.ts
  src/pages/PlaceList/PlaceList.tsx
  src/pages/PlaceList/loader.ts
  src/routes/index.tsx
  src/routes/navigation.tsx
  src/store/useModalControl.ts
  src/styles/GlobalStyles.ts
  src/utils/getQueryOptions.ts
  src/utils/index.ts
  src/utils/setDailyPopup.ts
Labels: BugFix, Feat, Modify

#174 [Feat] Place 등록 페이지 구현
  public/images/banner_1.jpg
  src/components/atoms/ButtonCheck/ButtonCheck.tsx
  src/components/organisms/ServiceCanUse/ServiceCanUse.tsx
  src/pages/AddPlace/AddPlace.tsx
Labels: Feat, Modify

#173 [BugFix] 스토리 최신순 오류
  src/pages/Stories/Stories.tsx
Labels: BugFix

#176 [BugFix] StoryWrite에서 사진 삭제 기능 버그
  src/pages/Stories/Stories.tsx
  src/pages/StoriesWrite/StoryWrite.tsx
Labels: BugFix

#177 [Modify] Reservation 날짜 표현 방식 변경, 사진 개수 버그 수정
  src/@types/database.d.ts
  src/components/molecules/MyPlaceList/MyPlaceList.tsx
  src/pages/ChatRoom/ChatRoom.tsx
  src/pages/ChatRoom/getChatRoomData.tsx
  src/pages/Reservations/Reservations.tsx
  src/pages/Reservations/getReservations.tsx
  src/pages/StoriesWrite/StoryWrite.tsx
  src/utils/getDateDiff.ts
Labels: BugFix, Modify

#179 [BugFix] 필터 오류 수정
  package.json
  public/images/loading/loading_spinner_1.svg
  public/images/loading/loading_spinner_2.svg
  public/images/loading/loading_spinner_3.svg
  src/@types/database.d.ts
  src/api/fetchPlaceList.ts
  src/components/molecules/GlobalNavBar/GlobalNavBar.tsx
  src/components/molecules/Header/Header.tsx
  src/components/molecules/LoadingSpinner/PetSpinner.tsx
  src/hooks/usePlaceSort.ts
  src/pages/ErrorBoundary/ErrorBoundary.tsx
  src/pages/Main/Main.tsx
  src/pages/MyPlaces/MyPlaces.tsx
  src/pages/PlaceList/PlaceList.tsx
  src/styles/GlobalStyles.ts
Labels: BugFix

#180 [Feat] Payment, reservation 구현 완료
  src/pages/ReservationDone/ReservationDone.tsx
Labels: Feat

#181 [Modify] small 수정
  database.d.ts
  src/components/molecules/AnimalRateInput/AnimalRateInput.tsx
  src/components/organisms/AnimalPick/AnimalPick.tsx
  src/components/organisms/DatePick/DatePick.tsx
  src/components/organisms/PlaceTitle/PlaceTitle.tsx
  src/components/organisms/ReservationInfo/ReservationInfo.tsx
  src/components/organisms/ServicePrice/ServicePrice.tsx
  src/pages/AddPlace/AddPlace.tsx
  src/pages/Payment/Payment.tsx
  src/pages/PlaceDetail/PlaceDetail.tsx
  src/pages/PlaceDetail/loader.ts
  src/routes/navigation.tsx
  src/store/useReservationStore.ts
Labels: Modify

#182 [modify] MyPage 프로필사진 오류 수정
  src/pages/ModifyProfile/ModifyProfile.tsx
  src/pages/MyPage/MyPage.tsx
Labels: BugFix

#184 [BugFix] 채팅방 버그 수정
  src/pages/ChatList/ChatList.tsx
  src/pages/ChatRoom/ChatRoom.tsx
  src/pages/ChatRoom/createChatRoom.tsx
  src/pages/ChatRoom/getChatRoomData.tsx
  src/pages/ChatRoom/useChatRoomData.tsx
Labels: BugFix

#183 [Modify] ModifyProfile페이지 프로필 사진 수정
  src/pages/ModifyProfile/ModifyProfile.tsx
Labels: BugFix
